# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/native-authenticator/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt
